# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-23 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreTestingFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StoreTrainingFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TestingResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_train_data', models.IntegerField()),
                ('no_of_test_data', models.IntegerField()),
                ('no_of_pos_classified', models.IntegerField()),
                ('no_of_neg_classified', models.IntegerField()),
                ('no_of_actual_pos', models.IntegerField()),
                ('no_of_actual_neg', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TweetCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_text', models.TextField()),
                ('tweet_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ValidationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_split_ratio', models.FloatField()),
                ('test_split_ratio', models.FloatField()),
                ('no_of_pos_train_data', models.IntegerField()),
                ('no_of_neg_train_data', models.IntegerField()),
                ('no_of_pos_test_data', models.IntegerField()),
                ('no_of_neg_test_data', models.IntegerField()),
                ('no_of_pos_classified', models.IntegerField()),
                ('no_of_neg_classified', models.IntegerField()),
                ('no_of_actual_pos', models.IntegerField()),
                ('no_of_actual_neg', models.IntegerField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f_measure', models.FloatField()),
                ('accuracy', models.FloatField()),
            ],
        ),
    ]
