# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-26 01:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterSentiment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testingresult',
            name='no_of_actual_neg',
        ),
        migrations.RemoveField(
            model_name='testingresult',
            name='no_of_actual_pos',
        ),
    ]
