# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-13 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterSentiment', '0002_auto_20161026_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationresult',
            name='no_of_train_data',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
    ]
